use_frameworks!

platform :ios, '9.0'

target 'TBIMLibrary_Example' do
  pod 'TBIMLibrary', :path => '../'

  target 'TBIMLibrary_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
